### ISSUE TITLE
Add additional 'modes'

### ISSUE THREAD

**Issue by Hotrian** [Hotrian/OpenVRDesktopDisplayPortal#23]
Just letting anyone who is following the repo know about future changes.

In a future release I intend to add additional modes, such as an integrated Video Player, a turn counter (similar to how [TurnCounterVR](https://www.reddit.com/r/Vive/comments/4lwti7/turncountervr_a_rotation_counter_with_overlay/) functions), possibly stats about your computer such as CPU/GPU temp, etc.

Each available 'mode' will be selectable via a dropdown similar to how the other dropdowns work. The current application mirror mode will be selectable and the application will default to it for the time being, but I may eventually rename the project when there are other substantial modes, and the default mode might be something different; though it will probably load up the last mode you used, to speed it up for users who only use one mode or another.

I'm also thinking about integrating [OpenVRTwitchChat](https://github.com/Hotrian/OpenVRTwitchChat) because it becomes difficult to maintain multiple sources that rely on the same base code that you are also maintaining :P. As I make upgrades to the [HeadlessOverlayToolkit](https://github.com/Hotrian/HeadlessOverlayToolkit) I'm currently having to push those upgrades (and make any code changes necessary for that specific repo) to three separate repos.

This issue will not remain open until I finish implementing these different modes, instead it will be closed when I implement "Multi-Mode" which will allow you to select from the available application modes.

If you disagree with me adding additional modes and you think I should keep this application strictly as an Application Mirror, please voice your concerns below.

**Comment by brad-simpson** [comment]
No disagreement here. Maintainable code is always a good thing. Keep up the good work!

**Comment by Hotrian** [comment]
Will be closing with the release of 1.0.5, which should be very soon (still doing final testing). A Dropdown to select different modes has been added and while there aren't any other modes available yet I tested this method on my local source and it seems to work fine, so I'm gonna stick with it for now and close this issue with release.
