### ISSUE TITLE
Add Companion Overlays

### ISSUE THREAD

**Issue by Hotrian** [Hotrian/OpenVRDesktopDisplayPortal#30]
Currently the system is only designed to utilize a single Overlay, but it would be nice to have additional Overlays that are not necessarily attached or at the same position/rotation to the primary overlay. For now I will refer to these as Companion Overlays since they are not the main focus of the program, and are just meant to ease accessibility and accommodate UI elements, as well as a few other things such as #29.

This is mostly a note to self, but also of course being used to track progress on the Repo.

**Comment by Bjaux** [comment]
I would really love to see Companion Overlays! I'm really curious how they'll impact the performance too.

**Comment by Hotrian** [comment]
As you can see from the last commits I just pushed, Companion Overlays are now functional in that #29 has been closed and is functioning, though I haven't yet added support for disconnected companions for UI purposes.

Source only for now of course, but #29 is coming with v1.0.6, and possibly some other companion :o.

**Comment by Hotrian** [comment]
This is very nearly complete (in the sense that Companion Overlays are functional and ready to make a Release appearance). The latest source adds support for Buttons/Sliders/Toggles that can be interacted with from VR, so a basic VR settings panel should make a v1.0.6 appearance. Right now I'm only adding support for Transparency control (and maybe a few others) on the VR Settings Panel, though in the future I would like to add support for Dropdowns and potentially add the entire "Additional Settings" panel and Animation Settings as well as Capture Settings to the VR Interfaces.

Will be closing with the v1.0.6 release, though the Companion Overlay system is far from complete.

**Comment by Hotrian** [comment]
v1.0.6 has now been released and I'm closing this issue. I still intend to add other Companion Overlays but for now the system is in place and works pretty well :). The current Companion Overlays include the Backside Overlay (which can be disabled) as well as the VR Settings Panel. The VR Settings Panel is simplistic, only including options for Transparency, Haptics Toggle, Grab Toggle, Scale Toggle, and switching the Backside color, but in the future I intend to add additional settings to the VR Settings Panel as well as other Companion Overlays. This issue is only regarding support for additional Overlays in general and does not encompass any additional Overlays directly.

To open the VR Settings Panel, aim at the Overlay for a few seconds (should be 3, but seems to take 3 to 5), and an "Open Settings" button will pop up below the Overlay. Click that button and the VR Settings Panel will pop out. This Settings Panel is a separate Overlay entirely; Evident by the fact it is at a different angle than the primary overlay (currently 15° on the X Axis), look at it from the side to confirm ;].
