### ISSUE TITLE
Compile Errors in Unity 5.4.1f1

### ISSUE THREAD

**Issue by robnewton** [Hotrian/OpenVRDesktopDisplayPortal#53]
Trying to compile from OpenVRDesktopDisplayPortal-1.0.6-alpha after opening in Unity 5.4.1f1. The following errors are preventing the compile:

> The type or namespace name 'SteamVR_UpdatePoses' could not be found (are you missing a using directive or an assembly reference?)

I've tried adding UNITY_5_4_OR_NEWER to a few lines above it but different errors are encountered:

> 'SteamVR' does not contain a definition for 'Unity'

**Comment by Hotrian** [comment]
This is currently built for Unity 5.3.6f1. First, you should be using the SteamVR code in this project and not one from some other source, because the SteamVR code here is different.

Next, @bjennings76 already addressed this in #43

**Comment by Hotrian** [comment]
This was also addressed in on HOTK's issue tracker [here](https://github.com/Hotrian/HeadlessOverlayToolkit/issues/4) regarding the changes required for SteamVR_UpdatePoses.

**Comment by robnewton** [comment]
Great, thanks for the fast reply.

**Comment by Hotrian** [comment]
Were you able to get this fixed? Would love to close this issue if so.

**Comment by robnewton** [comment]
I had to install 5.3 and just havent had a chance to get back to it yet. I read through the other thread though and the introduction of embedded VR support and the hard coded init makes sense. I will move forward with 5.3 and I expect it to be fine.
