### ISSUE TITLE
Make this compatible with non-VR fullscreen mode

### ISSUE THREAD

**Issue by amadeus1171** [Hotrian/OpenVRDesktopDisplayPortal#57]
Hi,

Can this be used without a VR headset and render into the world as full screen?

**Comment by Hotrian** [comment]
This works through SteamVR, so it can only be seen through the SteamVR compositor. One way to get around this is to use the [SteamVR null driver](https://developer.valvesoftware.com/wiki/SteamVR/steamvr.vrsettings) which then replaces a VR headset, and the compositor then displays to the desktop, but this definitely needs SteamVR to function, and many games probably then replace some of the desktop controls or function differently expecting you to have controllers. 

You could always use [OnTopReplica](http://ontopreplica.codeplex.com) for a similar experience, though it wouldn't be in the world then.
