### ISSUE TITLE
Theres no executable in the ZIP?

### ISSUE THREAD

**Issue by TheBitcoinBaron** [Hotrian/OpenVRDesktopDisplayPortal#67]
As per title theres no program in the zip, please provide a compiled program as the clone option forces either zip or some 3rd party app.

**Comment by Hotrian** [comment]
You're downloading the source code. Head over to the [releases](https://github.com/Hotrian/OpenVRDesktopDisplayPortal/releases) page for the binaries - this is how GitHub handles things :P
