### ISSUE TITLE
No .exe

### ISSUE THREAD

**Issue by JunebugMcQuinn** [Hotrian/OpenVRDesktopDisplayPortal#68]
Downloaded off source code off the normal download looked everywhere no .exe

**Comment by Hotrian** [comment]
The build artifacts are located under the [Releases](https://github.com/Hotrian/OpenVRDesktopDisplayPortal/releases) section, which is located on the right on the refreshed GitHub website.

This is explicitly mentioned in the readme:

> To use this, you can **[download the latest release](https://github.com/Hotrian/OpenVRDesktopDisplayPortal/releases)** and check out the **[Instructions Article](https://github.com/Hotrian/OpenVRDesktopDisplayPortal/wiki/Instructions)** to get started. Or, if you are more code savvy, [grab Unity 5.3.6f1](https://unity3d.com/get-unity/download/archive) and roll your own by cloning the repo or [downloading the source as a zip](https://github.com/Hotrian/OpenVRDesktopDisplayPortal/archive/master.zip).
